/**
 * Composing pool deposits and withdrawals.
 *
 * The math for what a deposit *will* do lives in `@counters/core/pool`; this is
 * the part that talks to the node. Every compose carries a `min_*` bound taken
 * from the slippage setting, so a stale local estimate can only cost a revert,
 * never a bad fill.
 */

import { big, parseJsonLossless, type Raw } from "@counters/core/numeric";
import type { Pool } from "@counters/core/pool";
import type { ComposeResult } from "@/lib/inscribe/psbt";

async function cp<T>(path: string): Promise<T> {
  const res = await fetch(`/api/cp/${path}`, { cache: "no-store" });
  const text = await res.text();
  const body = parseJsonLossless<{ result: T; error?: string }>(text);
  if (!res.ok) throw new Error((body as { error?: string })?.error ?? `Counterparty said ${res.status}`);
  return body.result;
}

/** The pool for a counter, or null when nobody has opened one. */
export async function fetchPool(asset: string): Promise<Pool | null> {
  try {
    return await cp<Pool | null>(`pools/${encodeURIComponent(asset)}/XCP?verbose=true`);
  } catch {
    return null;
  }
}

/** Exactly what `/quote/deposit` returns. The names are the node's, not ours. */
export interface DepositQuote {
  first_deposit: boolean;
  /** Raw quantity of the counter asset that will actually be debited. */
  quantity_a_required: Raw;
  /** Raw XCP that will actually be debited. */
  quantity_b_required: Raw;
  /** LP tokens the deposit will mint. */
  quantity_minted_estimate: Raw;
}

/**
 * What a proportional deposit requires, from the node.
 *
 * This is the authority, and local math is not a substitute for it. The
 * tempting shortcut — treating `sqrt(reserve_a * reserve_b)` as the pool's LP
 * supply — is only true in the instant after a first deposit: swaps grow the
 * reserves while the LP supply stays fixed, so the two drift apart for as long
 * as the pool is traded. On the live MEMENOME pool that shortcut already
 * overstates the mint by 16 basis points, and the error only grows. Since the
 * estimate sets the `min_lp_quantity` floor, an overstatement eventually
 * reverts a transaction the user has already paid a miner fee for.
 *
 * Only meaningful once a pool exists: an empty pool has no ratio, which is
 * exactly what makes a first deposit a price-setting act rather than a matched
 * one.
 */
export function fetchDepositQuote(asset: string, quantityA: bigint): Promise<DepositQuote> {
  return cp<DepositQuote>(
    `pools/${encodeURIComponent(asset)}/XCP/quote/deposit?quantity=${quantityA}&verbose=true`,
  );
}

export function fetchWithdrawQuote(asset: string, lpQuantity: bigint) {
  return cp<{ quantity_a: Raw; quantity_b: Raw }>(
    `pools/${encodeURIComponent(asset)}/XCP/quote/withdraw?quantity=${lpQuantity}&verbose=true`,
  );
}

/**
 * The XCP gas fee consensus charges for a pool message. Shown before signing —
 * it is paid in XCP, not satoshis, and a wallet that is short of it fails at
 * validation rather than at compose.
 */
export function estimateDepositXcpFee(address: string): Promise<number> {
  return cp<number>(`addresses/${encodeURIComponent(address)}/compose/pooldeposit/estimatexcpfees`);
}

export function estimateWithdrawXcpFee(address: string): Promise<number> {
  return cp<number>(
    `addresses/${encodeURIComponent(address)}/compose/poolwithdraw/estimatexcpfees`,
  );
}

/**
 * What a compose returns. The prevout arrays are the load-bearing part: they
 * are what lets the transaction be rebuilt as a PSBT without looking anything
 * up, which is what both wallets are handed. Every compose here asks for
 * `verbose=true` to get them.
 */
export type ComposedTx = ComposeResult;

async function compose(address: string, type: string, params: URLSearchParams): Promise<ComposedTx> {
  const res = await fetch(`/api/cp/addresses/${encodeURIComponent(address)}/compose/${type}`, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: params.toString(),
  });
  const body = await res.json().catch(() => null);
  if (!res.ok) throw new Error(body?.error ?? `Counterparty refused the compose (${res.status})`);
  return body.result as ComposedTx;
}

export interface DepositRequest {
  address: string;
  asset: string;
  quantityA: bigint;
  quantityB: bigint;
  /** Floor on LP tokens minted. 0 disables the check. */
  minLpQuantity: bigint;
  /** Only for a first deposit; auto-generated by the node when omitted. */
  lpAsset?: string;
  satPerVbyte: number;
}

export function composeDeposit(req: DepositRequest): Promise<ComposedTx> {
  const params = new URLSearchParams({
    asset_a: req.asset,
    asset_b: "XCP",
    // Note the asymmetry consensus imposes: for a first deposit these two
    // numbers *set the price*, and for every later one they are maximums —
    // only the proportional amounts are debited.
    quantity_a: req.quantityA.toString(),
    quantity_b: req.quantityB.toString(),
    min_lp_quantity: req.minLpQuantity.toString(),
    sat_per_vbyte: String(req.satPerVbyte),
    exclude_utxos_with_balances: "true",
    verbose: "true",
  });
  if (req.lpAsset) params.set("lp_asset", req.lpAsset);
  return compose(req.address, "pooldeposit", params);
}

export interface WithdrawRequest {
  address: string;
  asset: string;
  /** LP tokens to destroy. */
  quantity: bigint;
  minQuantityA: bigint;
  minQuantityB: bigint;
  satPerVbyte: number;
}

export function composeWithdraw(req: WithdrawRequest): Promise<ComposedTx> {
  const params = new URLSearchParams({
    asset_a: req.asset,
    asset_b: "XCP",
    quantity: req.quantity.toString(),
    min_quantity_a: req.minQuantityA.toString(),
    min_quantity_b: req.minQuantityB.toString(),
    sat_per_vbyte: String(req.satPerVbyte),
    exclude_utxos_with_balances: "true",
    verbose: "true",
  });
  return compose(req.address, "poolwithdraw", params);
}

/** One address's balance of one asset, raw. */
export async function fetchBalance(address: string, asset: string): Promise<bigint> {
  try {
    const rows = await cp<{ quantity: Raw }[]>(
      `addresses/${encodeURIComponent(address)}/balances/${encodeURIComponent(asset)}?type=address`,
    );
    return rows.reduce((sum, r) => sum + big(r.quantity), 0n);
  } catch {
    return 0n;
  }
}

/** Reduce a quantity by a slippage percentage, for a `min_*` bound. */
export function withSlippage(quantity: bigint, percent: number): bigint {
  const bps = BigInt(Math.round(percent * 100));
  return (quantity * (10_000n - bps)) / 10_000n;
}
